---
title: "Gov 50 Final Project"
author: "El Richards"
description: "My final project for Gov50"
output:
  distill::distill_article:
    self_contained: false
---
```{r}
install.packages("distill", repos = "http://cran.us.r-project.org")
```

## Project thoughts
For my final project, I am interested in exploring data related to government spending on education. Hopefully, my project will look at government spending on education in the United States, with the aim to examine yearly trends, the distribution of funds among different levels of education, and the comparison between spending and educational outcomes. To do this, I am planning on using the U.S. government's education spending data, this should be easily accessible public information.

## Milestone 2
The data set I will be using the following: https://github.com/erikgahner/PolData. Specifially, the data set entitled "Education Policies and Systems across Modern History."

Research question: How has federal government spending on education in the United States evolved and changed over the past decades? What is its impact on educational outcomes at different levels of the education system?

Hypothesis: I will be trying to see if the increase in government spending on primary and secondary education in the United States, will positively correlate with improved standardized test scores among students, thereby reducing educational disparities. More over, I will be looking into targeted forms of investments meant to improve resource equity and allocation among schools.

Given the outline of my thinking above, I will be looking at Government Spending on Primary and Secondary Education (measured as a percentage of GDP). This variable will depict the level of financial investment made by the government in primary and secondary education. Given the data set that I have chosen, this can be measured annually and I expect the outcome to vary over time. In my research, the outcome variable will be Standardized Test Scores, this outcome variable will allow me to measure educational performance. I will attempt to look at this on multiple levels--state, district, or school level--and can be collected over multiple years to track changes over time.

To support my hypothesis, I will look for a positive correlation between increased government spending on education and improved standardized test scores among students over several years. Moreover, if a narrowing of the  gap between students in high-resource and low-resource schools as government spending on education increases, my hypothesis will also be proved correct. Paradoxically, if there is no significant correlation between government spending on education and changes in standardized test scores, I was wrong in the initial hypothesis that I presented. Regardless of whether or not my initial thinking was correct or not, these patterns will help to determine whether increased government spending on education has a positive impact on educational outcomes and equity across public/governmentally funded schools. 